blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/realsenseai/librealsense/discussions
    about: For general questions and community discussions
  - name: Documentation
    url: https://github.com/realsenseai/librealsense/tree/master/doc
    about: Browse the official documentation
